services:
  seed:
    build: backend
    command: yarn seed
    restart: "no"
    ports:
      - 9001:9001
    environment:
      REDIS_URL: redis://redis:6379
      CACHE_REDIS_URL: redis://redis:6379
      EVENTS_REDIS_URL: redis://redis:6379
      WE_REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://medusa-starter:medusa-password@postgres:5432/medusa-starter?sslmode=disable
      POSTGRES_URL: postgresql://medusa-starter:medusa-password@postgres:5432/medusa-starter?sslmode=disable
