services:
  frontend:
    build:
      context: storefront
      args:
        - MEDUSA_BACKEND_URL=http://host.docker.internal:9000
        - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_a7edbcd5170fd1a1c396891c41dcb05c2ca571b337f6e49918b02590c9f0f65f
      extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOSTNAME: 0.0.0.0
      MEDUSA_BACKEND_URL: http://host.docker.internal:9000
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://host.docker.internal:9000
      NEXT_PUBLIC_STRIPE_KEY: pk_test_51SNWfhCoPMy2us8cMREJTQ8nkZljXlRwCKl2hw6oELnCKw7nWTD1qfHyLPcAQndjuls8pVploEma0iZdtqdp1LO200H2Pdl2uT
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    volumes:
      - ./storefront-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3